#
# APPLICATIONS
#

$terminal = alacritty
$launcher = rofi -show drun -show-icons -theme ~/.config/rofi/style.rasi
$emojis = bemoji -c -n
$files = thunar
$browser = chromium
$editor = cursor --ozone-platform=wayland