#
# BINDS
#

$superShiftMod = SUPER_SHIFT
$superMod = SUPER
$shiftMod = SHIFT
$altMod = ALT

bind = $superMod, F, fullscreen
bind = $superMod, Q, killactive
bind = $superMod, A, exec, $launcher
bind = $superMod, S, exec, $terminal
bind = $superMod, D, exec, $files
bind = $superMod, W, exec, $browser
bind = $superMod, Z, exec, $editor
bind = $superMod, C, exec, copyq show
bind = $superMod, E, exec, $emojis
bind = $altMod, Q, exec, wlogout
bind = $shiftMod, PRINT, exec, hyprshot -z -m region
bind = , PRINT, exec, hyprshot -z -m output
binde = , Prior, exec, ddcutil --noverify --noconfig setvcp 10 + 10
binde = , Next, exec, ddcutil --noverify --noconfig setvcp 10 - 10
binde = , KP_Add, exec, wpctl set-volume -l 1.50 @DEFAULT_AUDIO_SINK@ 5%+
binde = , KP_Subtract, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-

bindm = $superMod, mouse:272, movewindow
bindm = $superMod, mouse:273, resizewindow

bind = $superMod, left, movefocus, l
bind = $superMod, right, movefocus, r
bind = $superMod, up, movefocus, u
bind = $superMod, down, movefocus, d

bind = $superMod, 1, workspace, 1
bind = $superMod, 2, workspace, 2
bind = $superMod, 3, workspace, 3
bind = $superMod, 4, workspace, 4
bind = $superMod, 5, workspace, 5
bind = $superMod, 6, workspace, 6
bind = $superMod, 7, workspace, 7
bind = $superMod, 8, workspace, 8
bind = $superMod, 9, workspace, 9
bind = $superMod, 0, workspace, 10

bind = $superShiftMod, 1, movetoworkspacesilent, 1
bind = $superShiftMod, 2, movetoworkspacesilent, 2
bind = $superShiftMod, 3, movetoworkspacesilent, 3
bind = $superShiftMod, 4, movetoworkspacesilent, 4
bind = $superShiftMod, 5, movetoworkspacesilent, 5
bind = $superShiftMod, 6, movetoworkspacesilent, 6
bind = $superShiftMod, 7, movetoworkspacesilent, 7
bind = $superShiftMod, 8, movetoworkspacesilent, 8
bind = $superShiftMod, 9, movetoworkspacesilent, 9
bind = $superShiftMod, 0, movetoworkspacesilent, 10