#
# SYSTEM STARTUP
#

exec-once = /usr/lib/hyprpolkitagent
exec-once = /usr/lib/xdg-desktop-portal-hyprland
exec-once = /usr/lib/packagekitd

exec-once = copyq --start-server & corectrl & hyprpaper & dunst & gamemoded
exec-once = corectrl --minimize-systray

# Auto restart waybar when hyprland restarted
exec = pkill waybar
exec = waybar