windowrule = float, ark
windowrule = float, ^(Alacritty)$
windowrule = float, copyq
windowrule = float, dolphin
windowrule = float, digikam
windowrule = float, gparted
windowrule = float, hdajackretask
windowrule = float, imv
windowrule = float, kitty
windowrule = float, kget
windowrule = float, ktorrent
windowrule = float, kvantum
windowrule = float, ^(net.nokyan.Resources)$
windowrule = float, missioncenter
windowrule = float, nwg-look
windowrule = float, ^(org.kde.kcharselect)$
windowrule = float, ^(org.kde.keditfiletype)$
windowrule = float, ^(org.kde.koko)$
windowrule = float, ^(org.kde.polkit-kde-authentication-agent-1)$
windowrule = float, pcmanfm-qt
windowrule = float, pavucontrol
windowrule = float, prismlauncher
windowrule = float, qt6ct
windowrule = float, thunar

windowrulev2 = float, title:^(Open File)$
windowrulev2 = size 789 534, title:^(Open File)$
windowrulev2 = float, title:^(Open Folder)$
windowrulev2 = size 789 534, title:^(Open Folder)$
windowrulev2 = float, title:^(Task Manager)$

windowrulev2 = size 929 542, class:^(Alacritty)$