source = ~/.config/hypr/config.d/monitor.conf
source = ~/.config/hypr/config.d/env.conf
source = ~/.config/hypr/config.d/apps.conf
source = ~/.config/hypr/config.d/binds.conf
source = ~/.config/hypr/config.d/startup.conf
source = ~/.config/hypr/config.d/windowrules.conf

general {
  border_size = 0
  gaps_in = 5
  gaps_out = 10
  layout = dwindle
}

decoration {
  rounding = 5

  blur {
    enabled = false
  }

  shadow {
    enabled = false
  }
}

input {
  kb_layout = tr
  numlock_by_default = true
  repeat_rate = 50
  repeat_delay = 500
  sensitivity = 0.2
}

misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  font_family = "Fira Sans"
  vrr = 1
}

xwayland {
  enabled = false
}

animations {
  enabled = false
}