--ozone-platform=wayland
--use-angle=vulkan
--enable-features=UseOzonePlatform,WaylandWindowDecorations,Vulkan,VulkanFromANGLE,DefaultANGLEVulkan,Quic,ZeroCopy,VaapiVideoEncoder,VaapiVideoDecoder,CanvasOopRasterization,SmoothScrolling,ShortcutsNotApps,WebAppUniversalInstall,BackForwardCache,FluentOverlayScrollbar,FluentScrollbar,ParallelDownloading

--extension-mime-request-handling=always-prompt-for-install
--process-per-site
--num-raster-threads=6

--allowliste­d-extension-id=clngdbkpkp­eebahjckkj­fobafhncgm­ne