[character]
format = " "
success_symbol = "(bold green)"
error_symbol = "(bold red)"

[username]
style_root = "green bold"
format = " [$user]($style) "
disabled = false
show_always = false

[git_branch]
symbol = " "
truncation_length = 20
truncation_symbol = "…"
style="bold purple"

[rust]
format = "via [ $version](bold red)"

[nodejs]
format = "via [ $version](bold green)"

[python]
format = "via [ $version](bold blue)"