[general]
import = [
  "~/.config/alacritty/themes/catppuccin.toml"
]

[window]
decorations = "none"
opacity = 0.95
startup_mode = "windowed"
dynamic_title = true

[font]
normal = { family = "Fira Mono", style = "Regular" }
bold = { family = "Fira Mono", style = "Bold" }
italic = { family = "Fira Mono", style = "Italic" }
size = 10
offset = { x = 0, y = 0 }

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[cursor]
style = { shape = "Beam", blinking = "On" }
thickness = 0.2